kind: helm-release
apiVersion: 1.1
build:
  context: .
  dockerfile: Dockerfile
install:
  chart: charts/maana-google-ai-vision
  values:
    - values.dev.yaml?
    - secrets.dev.yaml?
  set:
    replicaCount: 1
    image:
      repository: maana-google-ai-vision
      tag: $(tag)
      pullPolicy: Never
    ingress:
      annotations:
        kubernetes.io/ingress.class: traefik-azds
      hosts:
        # This expands to form the service's public URL: [space.s.][rootSpace.]maana-google-ai-vision.<random suffix>.<region>.azds.io
        # Customize the public URL by changing the 'maana-google-ai-vision' text between the $(rootSpacePrefix) and $(hostSuffix) tokens
        # For more information see https://aka.ms/devspaces/routing
        - $(spacePrefix)$(rootSpacePrefix)maana-google-ai-vision$(hostSuffix)
configurations:
  develop:
    build:
      useGitIgnore: false
    container:
      sync:
        - '!**/package.json'
      iterate:
        processesToKill: [node]
